spring:

  application:
    name: Orb-Platform

  datasource:
    url: jdbc:${DB_URL}?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: validate
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        generate_statistics: false
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baselineVersion: 1

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /documentacao-api
    operationsSorter: method
    tagsSorter: alpha
jwt:
  secret: ${JWT_SECRET}